version: '2'
services:
  odoo:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - --log-level=debug
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - EXTRA_OPTS=--log-level=debug
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  web-data:
  db-data:

